import type { AppData, Collection, Word } from "./types";
import { generateId } from "./utils";

const now = new Date().toISOString();
const daysAgo = (n: number) =>
  new Date(Date.now() - n * 86400000).toISOString();

export const defaultCollections: Collection[] = [
  {
    id: "col-business",
    name: "Business",
    slug: "business",
    description: "Words from the boardroom & beyond",
    icon: "briefcase",
    color: "#62aef0",
    wordIds: [],
  },
  {
    id: "col-psychology",
    name: "Psychology",
    slug: "psychology",
    description: "Mind, behavior & feelings",
    icon: "brain",
    color: "#d6b6f6",
    wordIds: [],
  },
  {
    id: "col-law",
    name: "Law",
    slug: "law",
    description: "Legal terms & courtroom language",
    icon: "scale",
    color: "#dd5b00",
    wordIds: [],
  },
  {
    id: "col-movies",
    name: "Movies",
    slug: "movies",
    description: "Cinematic vocabulary gems",
    icon: "film",
    color: "#ff64c8",
    wordIds: [],
  },
  {
    id: "col-books",
    name: "Books",
    slug: "books",
    description: "Literary words from your reading",
    icon: "book",
    color: "#2a9d99",
    wordIds: [],
  },
  {
    id: "col-daily",
    name: "Daily Life",
    slug: "daily-life",
    description: "Everyday words worth keeping",
    icon: "sun",
    color: "#1aae39",
    wordIds: [],
  },
  {
    id: "col-difficult",
    name: "Difficult Words",
    slug: "difficult-words",
    description: "Challenge yourself with these",
    icon: "sparkles",
    color: "#391c57",
    wordIds: [],
  },
];

export const mockWords: Word[] = [
  {
    id: generateId(),
    word: "Serendipity",
    meaning:
      "The occurrence of events by chance in a happy or beneficial way.",
    simpleMeaning: "A lucky surprise that turns out great",
    partOfSpeech: "noun",
    pronunciation: "/ˌser.ənˈdip.ə.ti/",
    example:
      "Finding that cozy café was pure serendipity on our rainy afternoon walk.",
    synonyms: ["fortune", "luck", "chance"],
    antonyms: ["misfortune", "bad luck"],
    tags: ["literature", "positive"],
    source: "A novel I was reading",
    note: "Love how this word sounds, like a little gift from the universe.",
    isFavorite: true,
    collectionIds: ["col-books"],
    masteryLevel: 60,
    nextReviewAt: daysAgo(-2),
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },
  {
    id: generateId(),
    word: "Ephemeral",
    meaning: "Lasting for a very short time; transitory.",
    simpleMeaning: "Something that doesn't last long",
    partOfSpeech: "adjective",
    pronunciation: "/ɪˈfem.ər.əl/",
    example: "The ephemeral beauty of cherry blossoms makes them even more precious.",
    synonyms: ["fleeting", "temporary", "brief"],
    antonyms: ["permanent", "lasting", "eternal"],
    tags: ["nature", "poetic"],
    source: "Nature documentary",
    note: "Reminds me of sunsets and childhood summers.",
    isFavorite: true,
    collectionIds: ["col-books", "col-difficult"],
    masteryLevel: 40,
    nextReviewAt: daysAgo(-1),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
  },
  {
    id: generateId(),
    word: "Resilient",
    meaning: "Able to withstand or recover quickly from difficult conditions.",
    simpleMeaning: "Bouncing back after hard times",
    partOfSpeech: "adjective",
    pronunciation: "/rɪˈzɪl.i.ənt/",
    example: "She remained resilient despite every setback along the way.",
    synonyms: ["tough", "strong", "adaptable"],
    antonyms: ["fragile", "weak"],
    tags: ["motivation", "psychology"],
    source: "Podcast about mindset",
    note: "A word I want to embody.",
    isFavorite: false,
    collectionIds: ["col-psychology"],
    masteryLevel: 75,
    nextReviewAt: daysAgo(0),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(3),
  },
  {
    id: generateId(),
    word: "Ubiquitous",
    meaning: "Present, appearing, or found everywhere.",
    simpleMeaning: "Everywhere you look",
    partOfSpeech: "adjective",
    pronunciation: "/juːˈbɪk.wɪ.təs/",
    example: "Smartphones have become ubiquitous in modern daily life.",
    synonyms: ["omnipresent", "pervasive", "everywhere"],
    antonyms: ["rare", "scarce"],
    tags: ["tech", "formal"],
    source: "Tech article",
    note: "",
    isFavorite: false,
    collectionIds: ["col-business", "col-difficult"],
    masteryLevel: 25,
    nextReviewAt: daysAgo(-3),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(8),
  },
  {
    id: generateId(),
    word: "Melancholy",
    meaning: "A feeling of pensive sadness, typically with no obvious cause.",
    simpleMeaning: "A gentle, thoughtful sadness",
    partOfSpeech: "noun",
    pronunciation: "/ˈmel.ənˌkɒl.i/",
    example: "A soft melancholy settled over the empty autumn streets.",
    synonyms: ["sadness", "wistfulness", "gloom"],
    antonyms: ["joy", "cheerfulness"],
    tags: ["emotion", "literature"],
    source: "Classic film",
    note: "Not always bad, sometimes beautiful.",
    isFavorite: true,
    collectionIds: ["col-movies", "col-books"],
    masteryLevel: 55,
    nextReviewAt: daysAgo(-1),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(4),
  },
  {
    id: generateId(),
    word: "Pragmatic",
    meaning: "Dealing with things sensibly and realistically.",
    simpleMeaning: "Practical and down-to-earth",
    partOfSpeech: "adjective",
    pronunciation: "/præɡˈmæt.ɪk/",
    example: "She took a pragmatic approach to solving the team's problems.",
    synonyms: ["practical", "sensible", "realistic"],
    antonyms: ["idealistic", "impractical"],
    tags: ["business", "work"],
    source: "Work meeting",
    note: "",
    isFavorite: false,
    collectionIds: ["col-business"],
    masteryLevel: 80,
    nextReviewAt: daysAgo(2),
    createdAt: daysAgo(14),
    updatedAt: daysAgo(6),
  },
];

export function createInitialData(): AppData {
  const words: Word[] = [];
  const collections = defaultCollections.map((c) => ({ ...c, wordIds: [] }));

  return {
    version: 2,
    words,
    collections,
    tags: [],
    reviewHistory: [],
    stats: {
      totalWordsSaved: 0,
      wordsReviewed: 0,
      favoriteWords: 0,
      learningStreak: 0,
      lastActiveDate: now.split("T")[0],
      mostUsedTag: "none",
    },
    settings: {
      userName: "Word Collector",
      initialized: true,
    },
  };
}
